name: Update README with Contributions

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run GitHub Contributor Readme Action
        uses: ghapi-org/github-contributor-readme-action@v1
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: Kemol001/Kemol001
          MAX_REPOS: 6 
          SHOW_FORKS: false 
          COMMIT_MESSAGE: 'Update contributions list'
